version: 2
customFilters:
  filter: ".vulnerabilities |= map(select((.isUpgradable == true or .isPatchable == true) and (.\"exploit\" == \"Proof Concept\")))"
  pass: "[.vulnerabilities[]? | select((.isUpgradable == true or .isPatchable == true) and (.\"exploit\" == \"Proof Concept\"))] | length"
  msg: "Vulnerabilities found matching exploit/fixable filter"
